schema_version: 1

context:
  version_str: "\"load_file_regex(load_file='src/matrixconverters/_version | py', regex_pattern='^[_]{0,2}version[_]{0,2}\\\\s*=\\\\s*[\\'\\\\\"]([^\\'\\\\\"]*)[\\'\\\\\"]')\""

package:
  name: matrixconverters
  version: ${{ version_str[1] }}

source:
  path: ./matrixconverters

build:
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python
    - pip
    - setuptools>=61.0
  run:
    - python
    - numpy
    - xarray >=2022
    - h5netcdf
    #- pytest-cov
    - setuptools>=61.0

tests:
  - script:
    - pytest --pyargs matrixconverters
    requirements:
      run:
        - pytest-cov

about:
  license: NGPL
  homepage: https://maxbo.github.io/matrixconverters
  summary: package to read and write PTV-Visum Matrix Formats
